name: GitOps

###
# GitOps - automatic infrastructure management GitHub Action
#
# See https://github.com/microsoft/NubesGen/blob/main/docs/gitops-overview.md
# for more information about using GitOps with NubesGen.
###

on:
  push:
    branches:
      - 'env-*'

jobs:
  manage-infrastructure:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set environment variables
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/*/}
          echo "ENVIRONMENT=${TAG_NAME:4}" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=$(echo $AZURE_CREDENTIALS | jq -r .clientId)" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$(echo $AZURE_CREDENTIALS | jq -r .subscriptionId)" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(echo $AZURE_CREDENTIALS | jq -r .tenantId)" >> $GITHUB_ENV
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Initialize Terraform
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          TF_STORAGE_ACCOUNT: ${{ secrets.TF_STORAGE_ACCOUNT }}
        run: |
          export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
          terraform init \
          -input=false \
          -backend-config="resource_group_name=rg-terraform-001" \
          -backend-config="storage_account_name=$TF_STORAGE_ACCOUNT" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=$ENVIRONMENT.terraform.tfstate"
        working-directory: '${{ github.workspace }}/terraform'
      - name: Apply Terraform
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          TF_STORAGE_ACCOUNT: ${{ secrets.TF_STORAGE_ACCOUNT }}
        run: |
          export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
          terraform apply \
          -input=false \
          -auto-approve \
          -var="environment=$ENVIRONMENT"
        working-directory: '${{ github.workspace }}/terraform'
  build:
    needs: manage-infrastructure
    runs-on: ubuntu-20.04
    env:
      APPLICATION_NAME: 'demo-8772-7871-8616-7517'
      CONTAINER_REGISTRY: 'demo8772787186167517'
    steps:
      - name: Set environment variables
        run: |
          TAG_NAME=${GITHUB_REF#refs/*/}
          echo "ENVIRONMENT=${TAG_NAME:4}" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build with Docker
        run: docker build -t acr${{ env.CONTAINER_REGISTRY }}${{ env.ENVIRONMENT }}001.azurecr.io/${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}:${{ github.sha }} .
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Push to Azure Container Registry
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          az acr login -n acr${{ env.CONTAINER_REGISTRY }}${{ env.ENVIRONMENT }}001.azurecr.io
          docker push acr${{ env.CONTAINER_REGISTRY }}${{ env.ENVIRONMENT }}001.azurecr.io/${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}:${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    env:
      APPLICATION_NAME: 'demo-8772-7871-8616-7517'
      CONTAINER_REGISTRY: 'demo8772787186167517'
    steps:
      - name: Set environment variables
        run: |
          TAG_NAME=${GITHUB_REF#refs/*/}
          echo "ENVIRONMENT=${TAG_NAME:4}" >> $GITHUB_ENV
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-demo-8772-7871-8616-7517-${{ env.ENVIRONMENT }}-001'
          images: 'acr${{ env.CONTAINER_REGISTRY }}${{ env.ENVIRONMENT }}001.azurecr.io/${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}:${{ github.sha }}'
